// Static previews mirror the canonical AccountContext policy projection. Keep
// these complete so demo routing never advertises authority the server would
// deny or hides authority a real account would receive.
export const ACCOUNT_DEMO_FIXTURES = Object.freeze({
  visitor: {
    contract_id: 'moontown.account-context.v1',
    user_id: 'visitor-preview',
    display_name: 'Visitor',
    account_kind: 'visitor',
    plan: 'visitor',
    roles: ['member'],
    entitlements: ['town.public.explore', 'town.public.discover'],
    active_tenant_id: null,
    active_tenant_name: null,
    tenant_choices: [],
    home_surface: 'public-town',
    visitor: true,
  },
  paid: {
    contract_id: 'moontown.account-context.v1',
    user_id: 'paid-preview',
    display_name: 'MoonTown Member',
    account_kind: 'paid-user',
    plan: 'paid',
    roles: ['member'],
    entitlements: [
      'town.public.explore',
      'town.public.discover',
      'agent.personal.use',
      'workspace.personal.manage',
      'marketplace.action.use',
      'billing.personal.manage',
    ],
    active_tenant_id: null,
    active_tenant_name: null,
    tenant_choices: [],
    home_surface: 'personal-town',
    visitor: false,
  },
  enterprise: {
    contract_id: 'moontown.account-context.v1',
    user_id: 'enterprise-preview',
    display_name: 'Enterprise Member',
    account_kind: 'enterprise',
    plan: 'enterprise',
    roles: ['member', 'organization-admin'],
    entitlements: [
      'town.public.explore',
      'town.public.discover',
      'agent.personal.use',
      'workspace.personal.manage',
      'marketplace.action.use',
      'billing.personal.manage',
      'workspace.team.use',
      'agent.shared.use',
      'organization.members.view',
      'organization.usage.view',
      'organization.compliance.view',
      'town.content.publish',
      'organization.manage',
      'organization.members.manage',
      'organization.billing.manage',
    ],
    active_tenant_id: 'energy-labs',
    active_tenant_name: 'Energy Labs',
    tenant_choices: [
      {
        tenant_id: 'energy-labs',
        tenant_name: 'Energy Labs',
        plan: 'enterprise',
        roles: ['member', 'organization-admin'],
      },
    ],
    home_surface: 'enterprise-town',
    visitor: false,
  },
  admin: {
    contract_id: 'moontown.account-context.v1',
    user_id: 'admin-preview',
    display_name: 'District Operator',
    account_kind: 'admin',
    plan: 'paid',
    roles: ['member', 'platform-admin'],
    entitlements: [
      'town.public.explore',
      'town.public.discover',
      'agent.personal.use',
      'workspace.personal.manage',
      'marketplace.action.use',
      'billing.personal.manage',
      'town.content.publish',
      'organization.manage',
      'organization.members.manage',
      'organization.billing.manage',
      'platform.admin.access',
      'platform.users.manage',
      'platform.tenants.manage',
      'platform.content.moderate',
      'platform.analytics.view',
      'platform.audit.view',
      'platform.health.manage',
    ],
    active_tenant_id: null,
    active_tenant_name: null,
    tenant_choices: [],
    home_surface: 'admin-console',
    visitor: false,
  },
})
